import { FlightEntity } from '../../domain/entities/flight.entity';

export const flightSeedData = [
  // Voos domésticos diretos CNF ↔ GRU
  {
    flightNumber: 'LA3001',
    airline: 'LATAM',
    origin: 'CNF',
    destination: 'GRU',
    departureTime: '2024-12-15T06:00:00Z',
    arrivalTime: '2024-12-15T07:20:00Z',
    price: 800,
    currency: 'BRL',
    availableSeats: 150,
    totalSeats: 180,
    aircraft: 'Airbus A320',
    duration: '01:20',
    stops: 0,
    baggageIncluded: true,
    mealIncluded: false,
    refundable: false,
    bookingClass: 'economy' as const,
  },
  {
    flightNumber: 'G31234',
    airline: 'Gol',
    origin: 'CNF',
    destination: 'GRU',
    departureTime: '2024-12-15T09:30:00Z',
    arrivalTime: '2024-12-15T10:50:00Z',
    price: 1200,
    currency: 'BRL',
    availableSeats: 120,
    totalSeats: 160,
    aircraft: 'Boeing 737-800',
    duration: '01:20',
    stops: 0,
    baggageIncluded: true,
    mealIncluded: true,
    refundable: true,
    bookingClass: 'economy' as const,
  },
  {
    flightNumber: 'AD4567',
    airline: 'Azul',
    origin: 'GRU',
    destination: 'CNF',
    departureTime: '2024-12-15T18:00:00Z',
    arrivalTime: '2024-12-15T19:20:00Z',
    price: 950,
    currency: 'BRL',
    availableSeats: 95,
    totalSeats: 140,
    aircraft: 'Embraer E195',
    duration: '01:20',
    stops: 0,
    baggageIncluded: true,
    mealIncluded: false,
    refundable: false,
    bookingClass: 'economy' as const,
  },

  // Voos domésticos diretos CNF ↔ GIG
  {
    flightNumber: 'LA3456',
    airline: 'LATAM',
    origin: 'CNF',
    destination: 'GIG',
    departureTime: '2024-12-16T14:00:00Z',
    arrivalTime: '2024-12-16T15:30:00Z',
    price: 1100,
    currency: 'BRL',
    availableSeats: 78,
    totalSeats: 180,
    aircraft: 'Airbus A320',
    duration: '01:30',
    stops: 0,
    baggageIncluded: true,
    mealIncluded: false,
    refundable: false,
    bookingClass: 'economy' as const,
  },
  {
    flightNumber: 'G31567',
    airline: 'Gol',
    origin: 'GIG',
    destination: 'CNF',
    departureTime: '2024-12-16T20:15:00Z',
    arrivalTime: '2024-12-16T21:45:00Z',
    price: 1350,
    currency: 'BRL',
    availableSeats: 42,
    totalSeats: 160,
    aircraft: 'Boeing 737-800',
    duration: '01:30',
    stops: 0,
    baggageIncluded: true,
    mealIncluded: true,
    refundable: true,
    bookingClass: 'economy' as const,
  },
  {
    flightNumber: 'AD7890',
    airline: 'Azul',
    origin: 'CNF',
    destination: 'GIG',
    departureTime: '2024-12-17T11:45:00Z',
    arrivalTime: '2024-12-17T13:15:00Z',
    price: 1250,
    currency: 'BRL',
    availableSeats: 63,
    totalSeats: 140,
    aircraft: 'Embraer E195',
    duration: '01:30',
    stops: 0,
    baggageIncluded: true,
    mealIncluded: false,
    refundable: false,
    bookingClass: 'economy' as const,
  },

  // Voos internacionais CNF → SFO com conexões
  {
    flightNumber: 'LA8001',
    airline: 'LATAM',
    origin: 'CNF',
    destination: 'SFO',
    departureTime: '2024-12-20T22:30:00Z',
    arrivalTime: '2024-12-21T14:45:00Z',
    price: 6800,
    currency: 'BRL',
    availableSeats: 35,
    totalSeats: 300,
    aircraft: 'Boeing 787-9',
    duration: '16:15',
    stops: 1,
    stopCities: ['GRU'],
    baggageIncluded: true,
    mealIncluded: true,
    refundable: true,
    bookingClass: 'economy' as const,
  },
  {
    flightNumber: 'AA2341',
    airline: 'American Airlines',
    origin: 'CNF',
    destination: 'SFO',
    departureTime: '2024-12-21T08:20:00Z',
    arrivalTime: '2024-12-22T02:10:00Z',
    price: 7200,
    currency: 'BRL',
    availableSeats: 18,
    totalSeats: 280,
    aircraft: 'Boeing 777-300ER',
    duration: '17:50',
    stops: 1,
    stopCities: ['MIA'],
    baggageIncluded: true,
    mealIncluded: true,
    refundable: true,
    bookingClass: 'economy' as const,
  },
  {
    flightNumber: 'UA5678',
    airline: 'United Airlines',
    origin: 'CNF',
    destination: 'SFO',
    departureTime: '2024-12-22T15:50:00Z',
    arrivalTime: '2024-12-23T09:30:00Z',
    price: 8500,
    currency: 'BRL',
    availableSeats: 12,
    totalSeats: 320,
    aircraft: 'Boeing 777-200',
    duration: '17:40',
    stops: 1,
    stopCities: ['IAH'],
    baggageIncluded: true,
    mealIncluded: true,
    refundable: true,
    bookingClass: 'economy' as const,
  },
];

export async function seedFlights(): Promise<FlightEntity[]> {
  console.log('🌱 Seeding flights...');

  const flights: FlightEntity[] = [];

  for (const flightData of flightSeedData) {
    try {
      const flight = FlightEntity.create(flightData);
      flights.push(flight);
    } catch (error) {
      console.error(`Error creating flight ${flightData.flightNumber}:`, error);
    }
  }

  console.log(`✅ Created ${flights.length} flights`);
  return flights;
}
