import { FlightEntity } from '../../domain/entities/flight.entity';

export const flightSeedData = [
  // ==============================================
  // VOOS CNF → SFO (IDA) - 01/10/2025
  // ==============================================

  // Voo 1 - Madrugada
  {
    flightNumber: 'LA8001',
    airline: 'LATAM',
    origin: 'CNF',
    destination: 'SFO',
    departureTime: '2025-10-01T02:30:00Z',
    arrivalTime: '2025-10-01T18:45:00Z',
    price: 3200,
    currency: 'BRL',
    availableSeats: 35,
    totalSeats: 300,
    aircraft: 'Boeing 787-9',
    duration: '16:15',
    stops: 1,
    stopCities: ['GRU'],
    baggageIncluded: true,
    mealIncluded: true,
    refundable: true,
    bookingClass: 'economy' as const,
  },
  {
    flightNumber: 'G31234',
    airline: 'Gol',
    origin: 'CNF',
    destination: 'GRU',
    departureTime: '2024-12-15T09:30:00Z',
    arrivalTime: '2024-12-15T10:50:00Z',
    price: 1200,
    currency: 'BRL',
    availableSeats: 120,
    totalSeats: 160,
    aircraft: 'Boeing 737-800',
    duration: '01:20',
    stops: 0,
    baggageIncluded: true,
    mealIncluded: true,
    refundable: true,
    bookingClass: 'economy' as const,
  },
  {
    flightNumber: 'AD4567',
    airline: 'Azul',
    origin: 'GRU',
    destination: 'CNF',
    departureTime: '2024-12-15T18:00:00Z',
    arrivalTime: '2024-12-15T19:20:00Z',
    price: 950,
    currency: 'BRL',
    availableSeats: 95,
    totalSeats: 140,
    aircraft: 'Embraer E195',
    duration: '01:20',
    stops: 0,
    baggageIncluded: true,
    mealIncluded: false,
    refundable: false,
    bookingClass: 'economy' as const,
  },

  // Voos domésticos diretos CNF ↔ GIG
  {
    flightNumber: 'LA3456',
    airline: 'LATAM',
    origin: 'CNF',
    destination: 'GIG',
    departureTime: '2024-12-16T14:00:00Z',
    arrivalTime: '2024-12-16T15:30:00Z',
    price: 1100,
    currency: 'BRL',
    availableSeats: 78,
    totalSeats: 180,
    aircraft: 'Airbus A320',
    duration: '01:30',
    stops: 0,
    baggageIncluded: true,
    mealIncluded: false,
    refundable: false,
    bookingClass: 'economy' as const,
  },
  {
    flightNumber: 'G31567',
    airline: 'Gol',
    origin: 'GIG',
    destination: 'CNF',
    departureTime: '2024-12-16T20:15:00Z',
    arrivalTime: '2024-12-16T21:45:00Z',
    price: 1350,
    currency: 'BRL',
    availableSeats: 42,
    totalSeats: 160,
    aircraft: 'Boeing 737-800',
    duration: '01:30',
    stops: 0,
    baggageIncluded: true,
    mealIncluded: true,
    refundable: true,
    bookingClass: 'economy' as const,
  },
  {
    flightNumber: 'AD7890',
    airline: 'Azul',
    origin: 'CNF',
    destination: 'GIG',
    departureTime: '2024-12-17T11:45:00Z',
    arrivalTime: '2024-12-17T13:15:00Z',
    price: 1250,
    currency: 'BRL',
    availableSeats: 63,
    totalSeats: 140,
    aircraft: 'Embraer E195',
    duration: '01:30',
    stops: 0,
    baggageIncluded: true,
    mealIncluded: false,
    refundable: false,
    bookingClass: 'economy' as const,
  },

  // === VOOS INTERNACIONAIS CNF → SFO (IDA 2025-10-01) ===
  {
    flightNumber: 'LA8001',
    airline: 'LATAM',
    origin: 'CNF',
    destination: 'SFO',
    departureTime: '2025-10-01T08:30:00Z',
    arrivalTime: '2025-10-01T18:45:00Z',
    price: 6800,
    currency: 'BRL',
    availableSeats: 35,
    totalSeats: 300,
    aircraft: 'Boeing 787-9',
    duration: '16:15',
    stops: 1,
    stopCities: ['GRU'],
    baggageIncluded: true,
    mealIncluded: true,
    refundable: true,
    bookingClass: 'economy' as const,
  },
  {
    flightNumber: 'AA2341',
    airline: 'American Airlines',
    origin: 'CNF',
    destination: 'SFO',
    departureTime: '2025-10-01T14:20:00Z',
    arrivalTime: '2025-10-02T08:10:00Z',
    price: 7200,
    currency: 'BRL',
    availableSeats: 28,
    totalSeats: 280,
    aircraft: 'Boeing 777-300ER',
    duration: '17:50',
    stops: 1,
    stopCities: ['MIA'],
    baggageIncluded: true,
    mealIncluded: true,
    refundable: true,
    bookingClass: 'economy' as const,
  },
  {
    flightNumber: 'UA5678',
    airline: 'United Airlines',
    origin: 'CNF',
    destination: 'SFO',
    departureTime: '2025-10-01T22:50:00Z',
    arrivalTime: '2025-10-02T16:30:00Z',
    price: 8500,
    currency: 'BRL',
    availableSeats: 42,
    totalSeats: 320,
    aircraft: 'Boeing 777-200',
    duration: '17:40',
    stops: 1,
    stopCities: ['IAH'],
    baggageIncluded: true,
    mealIncluded: true,
    refundable: true,
    bookingClass: 'economy' as const,
  },
  {
    flightNumber: 'DL9876',
    airline: 'Delta Air Lines',
    origin: 'CNF',
    destination: 'SFO',
    departureTime: '2025-10-01T11:15:00Z',
    arrivalTime: '2025-10-02T02:30:00Z',
    price: 7850,
    currency: 'BRL',
    availableSeats: 22,
    totalSeats: 290,
    aircraft: 'Airbus A350-900',
    duration: '15:15',
    stops: 1,
    stopCities: ['ATL'],
    baggageIncluded: true,
    mealIncluded: true,
    refundable: true,
    bookingClass: 'economy' as const,
  },

  // === VOOS INTERNACIONAIS SFO → CNF (VOLTA 2025-10-10) ===
  {
    flightNumber: 'LA8002',
    airline: 'LATAM',
    origin: 'SFO',
    destination: 'CNF',
    departureTime: '2025-10-10T09:20:00Z',
    arrivalTime: '2025-10-11T13:35:00Z',
    price: 7200,
    currency: 'BRL',
    availableSeats: 31,
    totalSeats: 300,
    aircraft: 'Boeing 787-9',
    duration: '14:15',
    stops: 1,
    stopCities: ['GRU'],
    baggageIncluded: true,
    mealIncluded: true,
    refundable: true,
    bookingClass: 'economy' as const,
  },
  {
    flightNumber: 'AA2342',
    airline: 'American Airlines',
    origin: 'SFO',
    destination: 'CNF',
    departureTime: '2025-10-10T16:45:00Z',
    arrivalTime: '2025-10-11T19:20:00Z',
    price: 7500,
    currency: 'BRL',
    availableSeats: 19,
    totalSeats: 280,
    aircraft: 'Boeing 777-300ER',
    duration: '15:35',
    stops: 1,
    stopCities: ['MIA'],
    baggageIncluded: true,
    mealIncluded: true,
    refundable: true,
    bookingClass: 'economy' as const,
  },
  {
    flightNumber: 'UA5679',
    airline: 'United Airlines',
    origin: 'SFO',
    destination: 'CNF',
    departureTime: '2025-10-10T13:30:00Z',
    arrivalTime: '2025-10-11T15:40:00Z',
    price: 8200,
    currency: 'BRL',
    availableSeats: 38,
    totalSeats: 320,
    aircraft: 'Boeing 777-200',
    duration: '16:10',
    stops: 1,
    stopCities: ['IAH'],
    baggageIncluded: true,
    mealIncluded: true,
    refundable: true,
    bookingClass: 'economy' as const,
  },

  // === MAIS VOOS DOMÉSTICOS ===
  // CNF ↔ BSB (Brasília)
  {
    flightNumber: 'LA3101',
    airline: 'LATAM',
    origin: 'CNF',
    destination: 'BSB',
    departureTime: '2025-10-01T07:00:00Z',
    arrivalTime: '2025-10-01T08:30:00Z',
    price: 650,
    currency: 'BRL',
    availableSeats: 89,
    totalSeats: 180,
    aircraft: 'Airbus A320',
    duration: '01:30',
    stops: 0,
    baggageIncluded: true,
    mealIncluded: false,
    refundable: false,
    bookingClass: 'economy' as const,
  },
  {
    flightNumber: 'G31890',
    airline: 'Gol',
    origin: 'BSB',
    destination: 'CNF',
    departureTime: '2025-10-10T19:15:00Z',
    arrivalTime: '2025-10-10T20:45:00Z',
    price: 720,
    currency: 'BRL',
    availableSeats: 67,
    totalSeats: 160,
    aircraft: 'Boeing 737-800',
    duration: '01:30',
    stops: 0,
    baggageIncluded: true,
    mealIncluded: false,
    refundable: false,
    bookingClass: 'economy' as const,
  },

  // CNF ↔ SSA (Salvador)
  {
    flightNumber: 'AD2345',
    airline: 'Azul',
    origin: 'CNF',
    destination: 'SSA',
    departureTime: '2025-10-02T10:30:00Z',
    arrivalTime: '2025-10-02T12:15:00Z',
    price: 890,
    currency: 'BRL',
    availableSeats: 54,
    totalSeats: 140,
    aircraft: 'Embraer E195',
    duration: '01:45',
    stops: 0,
    baggageIncluded: true,
    mealIncluded: false,
    refundable: false,
    bookingClass: 'economy' as const,
  },

  // CNF ↔ FOR (Fortaleza)
  {
    flightNumber: 'LA3789',
    airline: 'LATAM',
    origin: 'CNF',
    destination: 'FOR',
    departureTime: '2025-10-03T15:20:00Z',
    arrivalTime: '2025-10-03T18:05:00Z',
    price: 1150,
    currency: 'BRL',
    availableSeats: 43,
    totalSeats: 180,
    aircraft: 'Airbus A320',
    duration: '02:45',
    stops: 0,
    baggageIncluded: true,
    mealIncluded: true,
    refundable: false,
    bookingClass: 'economy' as const,
  },

  // === VOOS INTERNACIONAIS PARA OUTROS DESTINOS ===
  // CNF → MAD (Madrid)
  {
    flightNumber: 'IB6741',
    airline: 'Iberia',
    origin: 'CNF',
    destination: 'MAD',
    departureTime: '2025-10-01T23:45:00Z',
    arrivalTime: '2025-10-02T18:20:00Z',
    price: 5800,
    currency: 'BRL',
    availableSeats: 24,
    totalSeats: 350,
    aircraft: 'Airbus A350-900',
    duration: '12:35',
    stops: 1,
    stopCities: ['GRU'],
    baggageIncluded: true,
    mealIncluded: true,
    refundable: true,
    bookingClass: 'economy' as const,
  },

  // CNF → LHR (Londres)
  {
    flightNumber: 'BA2847',
    airline: 'British Airways',
    origin: 'CNF',
    destination: 'LHR',
    departureTime: '2025-10-01T20:30:00Z',
    arrivalTime: '2025-10-02T16:45:00Z',
    price: 6200,
    currency: 'BRL',
    availableSeats: 18,
    totalSeats: 275,
    aircraft: 'Boeing 787-8',
    duration: '14:15',
    stops: 1,
    stopCities: ['GIG'],
    baggageIncluded: true,
    mealIncluded: true,
    refundable: true,
    bookingClass: 'economy' as const,
  },

  // CNF → EZE (Buenos Aires)
  {
    flightNumber: 'AR1234',
    airline: 'Aerolíneas Argentinas',
    origin: 'CNF',
    destination: 'EZE',
    departureTime: '2025-10-02T12:15:00Z',
    arrivalTime: '2025-10-02T18:30:00Z',
    price: 2800,
    currency: 'BRL',
    availableSeats: 72,
    totalSeats: 180,
    aircraft: 'Airbus A330-200',
    duration: '06:15',
    stops: 1,
    stopCities: ['GRU'],
    baggageIncluded: true,
    mealIncluded: true,
    refundable: false,
    bookingClass: 'economy' as const,
  },

  // === VOOS BUSINESS CLASS ===
  {
    flightNumber: 'LA8101',
    airline: 'LATAM',
    origin: 'CNF',
    destination: 'SFO',
    departureTime: '2025-10-01T16:40:00Z',
    arrivalTime: '2025-10-02T06:25:00Z',
    price: 18500,
    currency: 'BRL',
    availableSeats: 8,
    totalSeats: 42,
    aircraft: 'Boeing 787-9',
    duration: '15:45',
    stops: 1,
    stopCities: ['GRU'],
    baggageIncluded: true,
    mealIncluded: true,
    refundable: true,
    bookingClass: 'business' as const,
  },

  // === VOOS PREMIUM ECONOMY ===
  {
    flightNumber: 'LA8201',
    airline: 'LATAM',
    origin: 'CNF',
    destination: 'SFO',
    departureTime: '2025-10-01T19:15:00Z',
    arrivalTime: '2025-10-02T09:00:00Z',
    price: 12800,
    currency: 'BRL',
    availableSeats: 15,
    totalSeats: 28,
    aircraft: 'Boeing 787-9',
    duration: '15:45',
    stops: 1,
    stopCities: ['GRU'],
    baggageIncluded: true,
    mealIncluded: true,
    refundable: true,
    bookingClass: 'premium_economy' as const,
  },
];

export async function seedFlights(): Promise<FlightEntity[]> {
  console.log('🌱 Seeding flights...');

  const flights: FlightEntity[] = [];

  for (const flightData of flightSeedData) {
    try {
      const flight = FlightEntity.create(flightData);
      flights.push(flight);
    } catch (error) {
      console.error(`Error creating flight ${flightData.flightNumber}:`, error);
    }
  }

  console.log(`✅ Created ${flights.length} flights`);
  return flights;
}
