import { HotelEntity } from '../../domain/entities/hotel.entity';

export const hotelSeedData = [
  // Hotéis em Belo Horizonte (15 hotéis)
  {
    hotelId: 'bh-001',
    name: 'Tryp by Wyndham Belo Horizonte Savassi',
    nightly: 280.0,
    total: 560.0,
    rating: 4.6,
    policy: 'Cancelamento gratuito até 24h antes - Café da manhã incluído',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-002',
    name: 'Radisson Blu Belo Horizonte',
    nightly: 320.0,
    total: 640.0,
    rating: 4.5,
    policy: 'Cancelamento gratuito até 48h antes',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-003',
    name: 'Holiday Inn Express Belo Horizonte Afonso Pena',
    nightly: 195.0,
    total: 390.0,
    rating: 4.2,
    policy: 'Cancelamento gratuito até 24h antes - Café da manhã incluído',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-004',
    name: 'Hotel Ouro Minas Palace',
    nightly: 450.0,
    total: 900.0,
    rating: 4.8,
    policy: 'Cancelamento gratuito até 72h antes',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-005',
    name: 'Intercity Belo Horizonte',
    nightly: 220.0,
    total: 440.0,
    rating: 4.3,
    policy: 'Cancelamento gratuito até 24h antes',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-006',
    name: 'Comfort Hotel Belo Horizonte',
    nightly: 165.0,
    total: 330.0,
    rating: 4.1,
    policy: 'Cancelamento gratuito até 24h antes - Café da manhã incluído',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-007',
    name: 'Dayrell Hotel e Centro de Convenções',
    nightly: 185.0,
    total: 370.0,
    rating: 4.0,
    policy: 'Cancelamento gratuito até 24h antes',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-008',
    name: 'Mercure Belo Horizonte Lourdes Hotel',
    nightly: 250.0,
    total: 500.0,
    rating: 4.4,
    policy: 'Cancelamento gratuito até 24h antes - Piscina e academia',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-009',
    name: 'ibis Belo Horizonte Savassi',
    nightly: 140.0,
    total: 280.0,
    rating: 3.9,
    policy: 'Cancelamento gratuito até 18h do dia da chegada',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-010',
    name: 'Quality Hotel Afonso Pena',
    nightly: 175.0,
    total: 350.0,
    rating: 4.1,
    policy: 'Cancelamento gratuito até 24h antes',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-011',
    name: 'San Diego Hotel',
    nightly: 120.0,
    total: 240.0,
    rating: 3.8,
    policy: 'Cancelamento gratuito até 24h antes - Centro histórico',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-012',
    name: 'Hotel Fasano Belo Horizonte',
    nightly: 680.0,
    total: 1360.0,
    rating: 4.9,
    policy: 'Cancelamento gratuito até 48h antes - Spa e restaurante',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-013',
    name: 'Novotel BH Savassi',
    nightly: 290.0,
    total: 580.0,
    rating: 4.5,
    policy: 'Cancelamento gratuito até 24h antes - Piscina na cobertura',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-014',
    name: 'Max Savassi Apart Service',
    nightly: 200.0,
    total: 400.0,
    rating: 4.2,
    policy: 'Cancelamento gratuito até 24h antes - Kitchenette',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-015',
    name: 'Hotel Beaga Convention Expominas',
    nightly: 160.0,
    total: 320.0,
    rating: 4.0,
    policy: 'Cancelamento gratuito até 24h antes - Próximo ao Expominas',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },

  // Hotéis em São Paulo (20 hotéis)
  {
    hotelId: 'sp-001',
    name: 'Copacabana Hotel',
    nightly: 350.0,
    total: 700.0,
    rating: 4.6,
    policy: 'Cancelamento gratuito até 24h antes - Piscina na cobertura',
    currency: 'BRL',
    city: 'São Paulo',
  },
  {
    hotelId: 'sp-002',
    name: 'Hotel Fasano São Paulo',
    nightly: 950.0,
    total: 1900.0,
    rating: 4.9,
    policy: 'Cancelamento gratuito até 48h antes - Restaurante premiado',
    currency: 'BRL',
    city: 'São Paulo',
  },
  {
    hotelId: 'sp-003',
    name: 'Grand Hyatt São Paulo',
    nightly: 720.0,
    total: 1440.0,
    rating: 4.8,
    policy: 'Cancelamento gratuito até 24h antes - Spa completo',
    currency: 'BRL',
    city: 'São Paulo',
  },
  {
    hotelId: 'sp-004',
    name: 'Renaissance São Paulo Hotel',
    nightly: 480.0,
    total: 960.0,
    rating: 4.5,
    policy: 'Cancelamento gratuito até 24h antes - Centro empresarial',
    currency: 'BRL',
    city: 'São Paulo',
  },
  {
    hotelId: 'sp-005',
    name: 'Pullman São Paulo Ibirapuera',
    nightly: 390.0,
    total: 780.0,
    rating: 4.4,
    policy: 'Cancelamento gratuito até 24h antes - Vista do parque',
    currency: 'BRL',
    city: 'São Paulo',
  },
  {
    hotelId: 'sp-006',
    name: 'Intercontinental São Paulo',
    nightly: 580.0,
    total: 1160.0,
    rating: 4.7,
    policy: 'Cancelamento gratuito até 48h antes - Jardins',
    currency: 'BRL',
    city: 'São Paulo',
  },
  {
    hotelId: 'sp-007',
    name: 'Hilton São Paulo Morumbi',
    nightly: 420.0,
    total: 840.0,
    rating: 4.3,
    policy: 'Cancelamento gratuito até 24h antes - Piscina e fitness',
    currency: 'BRL',
    city: 'São Paulo',
  },
  {
    hotelId: 'sp-008',
    name: 'Mercure São Paulo Alamedas',
    nightly: 280.0,
    total: 560.0,
    rating: 4.2,
    policy: 'Cancelamento gratuito até 24h antes - Jardim Paulista',
    currency: 'BRL',
    city: 'São Paulo',
  },
  {
    hotelId: 'sp-009',
    name: 'Novotel São Paulo Center',
    nightly: 320.0,
    total: 640.0,
    rating: 4.3,
    policy: 'Cancelamento gratuito até 24h antes - Centro histórico',
    currency: 'BRL',
    city: 'São Paulo',
  },
  {
    hotelId: 'sp-010',
    name: 'ibis São Paulo Paulista',
    nightly: 180.0,
    total: 360.0,
    rating: 3.9,
    policy: 'Cancelamento gratuito até 18h do dia da chegada',
    currency: 'BRL',
    city: 'São Paulo',
  },
  {
    hotelId: 'sp-011',
    name: 'Sheraton São Paulo WTC Hotel',
    nightly: 450.0,
    total: 900.0,
    rating: 4.5,
    policy: 'Cancelamento gratuito até 24h antes - WTC',
    currency: 'BRL',
    city: 'São Paulo',
  },
  {
    hotelId: 'sp-012',
    name: 'Hotel Unique',
    nightly: 850.0,
    total: 1700.0,
    rating: 4.8,
    policy: 'Cancelamento gratuito até 48h antes - Design exclusivo',
    currency: 'BRL',
    city: 'São Paulo',
  },
  {
    hotelId: 'sp-013',
    name: 'Maksoud Plaza Hotel',
    nightly: 380.0,
    total: 760.0,
    rating: 4.1,
    policy: 'Cancelamento gratuito até 24h antes - Bela Vista',
    currency: 'BRL',
    city: 'São Paulo',
  },
  {
    hotelId: 'sp-014',
    name: 'Hotel Emiliano',
    nightly: 920.0,
    total: 1840.0,
    rating: 4.9,
    policy: 'Cancelamento gratuito até 48h antes - Luxo em Jardins',
    currency: 'BRL',
    city: 'São Paulo',
  },
  {
    hotelId: 'sp-015',
    name: 'Radisson Blu São Paulo',
    nightly: 360.0,
    total: 720.0,
    rating: 4.4,
    policy: 'Cancelamento gratuito até 24h antes - Faria Lima',
    currency: 'BRL',
    city: 'São Paulo',
  },
  {
    hotelId: 'sp-016',
    name: 'Comfort Hotel Ibirapuera',
    nightly: 220.0,
    total: 440.0,
    rating: 4.0,
    policy: 'Cancelamento gratuito até 24h antes - Café incluído',
    currency: 'BRL',
    city: 'São Paulo',
  },
  {
    hotelId: 'sp-017',
    name: 'Tryp by Wyndham São Paulo Paulista',
    nightly: 310.0,
    total: 620.0,
    rating: 4.2,
    policy: 'Cancelamento gratuito até 24h antes - Av. Paulista',
    currency: 'BRL',
    city: 'São Paulo',
  },
  {
    hotelId: 'sp-018',
    name: 'JW Marriott Hotel São Paulo',
    nightly: 680.0,
    total: 1360.0,
    rating: 4.7,
    policy: 'Cancelamento gratuito até 24h antes - Spa e piscina',
    currency: 'BRL',
    city: 'São Paulo',
  },
  {
    hotelId: 'sp-019',
    name: 'Hotel Tivoli Mofarrej São Paulo',
    nightly: 520.0,
    total: 1040.0,
    rating: 4.6,
    policy: 'Cancelamento gratuito até 24h antes - Alameda Santos',
    currency: 'BRL',
    city: 'São Paulo',
  },
  {
    hotelId: 'sp-020',
    name: 'WZ Hotel Jardins',
    nightly: 420.0,
    total: 840.0,
    rating: 4.5,
    policy: 'Cancelamento gratuito até 24h antes - Design contemporâneo',
    currency: 'BRL',
    city: 'São Paulo',
  },

  // Hotéis em San Francisco (10 hotéis)
  {
    hotelId: 'sf-001',
    name: 'Hotel Zephyr San Francisco',
    nightly: 450.0,
    total: 900.0,
    rating: 4.4,
    policy: 'Free cancellation until 24h before - Breakfast included',
    currency: 'USD',
    city: 'San Francisco',
  },
  {
    hotelId: 'sf-002',
    name: 'The Ritz-Carlton San Francisco',
    nightly: 850.0,
    total: 1700.0,
    rating: 4.9,
    policy: 'Free cancellation until 48h before',
    currency: 'USD',
    city: 'San Francisco',
  },
  {
    hotelId: 'sf-003',
    name: 'Hotel Nikko San Francisco',
    nightly: 380.0,
    total: 760.0,
    rating: 4.3,
    policy: 'Free cancellation until 24h before',
    currency: 'USD',
    city: 'San Francisco',
  },
  {
    hotelId: 'sf-004',
    name: 'Grand Hyatt San Francisco',
    nightly: 520.0,
    total: 1040.0,
    rating: 4.6,
    policy: 'Free cancellation until 24h before - Union Square',
    currency: 'USD',
    city: 'San Francisco',
  },
  {
    hotelId: 'sf-005',
    name: 'Hotel Zeppelin San Francisco',
    nightly: 320.0,
    total: 640.0,
    rating: 4.2,
    policy: 'Free cancellation until 24h before - Boutique hotel',
    currency: 'USD',
    city: 'San Francisco',
  },
  {
    hotelId: 'sf-006',
    name: 'InterContinental San Francisco',
    nightly: 680.0,
    total: 1360.0,
    rating: 4.7,
    policy: 'Free cancellation until 48h before - SoMa district',
    currency: 'USD',
    city: 'San Francisco',
  },
  {
    hotelId: 'sf-007',
    name: 'The Westin St. Francis',
    nightly: 420.0,
    total: 840.0,
    rating: 4.4,
    policy: 'Free cancellation until 24h before - Historic hotel',
    currency: 'USD',
    city: 'San Francisco',
  },
  {
    hotelId: 'sf-008',
    name: 'Hotel Via San Francisco',
    nightly: 280.0,
    total: 560.0,
    rating: 4.1,
    policy: 'Free cancellation until 24h before - Union Square area',
    currency: 'USD',
    city: 'San Francisco',
  },
  {
    hotelId: 'sf-009',
    name: 'Four Seasons Hotel San Francisco',
    nightly: 950.0,
    total: 1900.0,
    rating: 4.8,
    policy: 'Free cancellation until 48h before - Luxury amenities',
    currency: 'USD',
    city: 'San Francisco',
  },
  {
    hotelId: 'sf-010',
    name: 'Hotel Adagio San Francisco',
    nightly: 350.0,
    total: 700.0,
    rating: 4.3,
    policy: 'Free cancellation until 24h before - Theater District',
    currency: 'USD',
    city: 'San Francisco',
  },
];

export const createHotelSeedEntities = (): HotelEntity[] => {
  return hotelSeedData.map((data) => HotelEntity.create(data));
};
