import { HotelEntity } from '../../domain/entities/hotel.entity';

export const hotelSeedData = [
  {
    name: 'Tryp by Wyndham Belo Horizonte Savassi',
    description:
      'Modern hotel in the heart of Savassi, perfect for business and leisure travelers',
    address: 'Rua Antônio de Albuquerque, 335',
    city: 'Belo Horizonte',
    state: 'Minas Gerais',
    country: 'Brazil',
    zipCode: '30112-010',
    latitude: -19.9395,
    longitude: -43.9378,
    rating: 4.2,
    totalRooms: 120,
    availableRooms: 45,
    pricePerNight: 280,
    currency: 'BRL',
    amenities: [
      'WiFi gratuito',
      'Ar condicionado',
      'Academia',
      'Estacionamento',
      'Room service',
    ],
    images: ['https://example.com/tryp1.jpg', 'https://example.com/tryp2.jpg'],
    checkInTime: '15:00',
    checkOutTime: '12:00',
    cancellationPolicy: 'Cancelamento gratuito até 24 horas antes do check-in',
    breakfastIncluded: true,
    wifiIncluded: true,
    parkingIncluded: true,
    petFriendly: false,
    stars: 4,
  },
  {
    name: 'Radisson Blu Belo Horizonte',
    description: 'Luxury hotel with panoramic city views and premium amenities',
    address: 'Avenida Bernardo Monteiro, 1567',
    city: 'Belo Horizonte',
    state: 'Minas Gerais',
    country: 'Brazil',
    zipCode: '30150-281',
    latitude: -19.9208,
    longitude: -43.9378,
    rating: 4.5,
    totalRooms: 180,
    availableRooms: 32,
    pricePerNight: 420,
    currency: 'BRL',
    amenities: [
      'WiFi gratuito',
      'Ar condicionado',
      'Piscina',
      'Spa',
      'Academia',
      'Business center',
    ],
    images: [
      'https://example.com/radisson1.jpg',
      'https://example.com/radisson2.jpg',
    ],
    checkInTime: '15:00',
    checkOutTime: '12:00',
    cancellationPolicy: 'Cancelamento gratuito até 48 horas antes do check-in',
    breakfastIncluded: true,
    wifiIncluded: true,
    parkingIncluded: true,
    petFriendly: true,
    stars: 5,
  },
  {
    name: 'Holiday Inn Express Belo Horizonte',
    description:
      'Comfortable and convenient hotel perfect for business travelers',
    address: 'Rua Curitiba, 1000',
    city: 'Belo Horizonte',
    state: 'Minas Gerais',
    country: 'Brazil',
    zipCode: '30170-120',
    latitude: -19.9245,
    longitude: -43.9445,
    rating: 4.1,
    totalRooms: 200,
    availableRooms: 89,
    pricePerNight: 195,
    currency: 'BRL',
    amenities: [
      'WiFi gratuito',
      'Ar condicionado',
      'Academia',
      'Business center',
    ],
    images: [
      'https://example.com/holiday1.jpg',
      'https://example.com/holiday2.jpg',
    ],
    checkInTime: '15:00',
    checkOutTime: '11:00',
    cancellationPolicy: 'Cancelamento gratuito até 18 horas antes do check-in',
    breakfastIncluded: true,
    wifiIncluded: true,
    parkingIncluded: false,
    petFriendly: false,
    stars: 3,
  },
  {
    name: 'Mercure Belo Horizonte Lourdes',
    description: 'Sophisticated hotel in the upscale Lourdes neighborhood',
    address: 'Rua Gonçalves Dias, 394',
    city: 'Belo Horizonte',
    state: 'Minas Gerais',
    country: 'Brazil',
    zipCode: '30140-091',
    latitude: -19.9311,
    longitude: -43.9455,
    rating: 4.3,
    totalRooms: 150,
    availableRooms: 67,
    pricePerNight: 320,
    currency: 'BRL',
    amenities: [
      'WiFi gratuito',
      'Ar condicionado',
      'Restaurante',
      'Bar',
      'Academia',
      'Room service',
    ],
    images: [
      'https://example.com/mercure1.jpg',
      'https://example.com/mercure2.jpg',
    ],
    checkInTime: '14:00',
    checkOutTime: '12:00',
    cancellationPolicy: 'Cancelamento gratuito até 24 horas antes do check-in',
    breakfastIncluded: false,
    wifiIncluded: true,
    parkingIncluded: true,
    petFriendly: false,
    stars: 4,
  },
  {
    name: 'ibis Belo Horizonte Centro',
    description:
      'Budget-friendly hotel with modern amenities in downtown location',
    address: 'Rua dos Tupis, 640',
    city: 'Belo Horizonte',
    state: 'Minas Gerais',
    country: 'Brazil',
    zipCode: '30190-060',
    latitude: -19.9167,
    longitude: -43.9345,
    rating: 3.9,
    totalRooms: 240,
    availableRooms: 156,
    pricePerNight: 140,
    currency: 'BRL',
    amenities: [
      'WiFi gratuito',
      'Ar condicionado',
      'Restaurante',
      'Bar',
      'Recepção 24h',
    ],
    images: ['https://example.com/ibis1.jpg', 'https://example.com/ibis2.jpg'],
    checkInTime: '14:00',
    checkOutTime: '12:00',
    cancellationPolicy: 'Cancelamento gratuito até 18 horas antes do check-in',
    breakfastIncluded: false,
    wifiIncluded: true,
    parkingIncluded: false,
    petFriendly: false,
    stars: 3,
  },
  {
    name: 'Hotel Fasano Belo Horizonte',
    description:
      'Ultra-luxury hotel offering world-class service and amenities',
    address: 'Avenida Getúlio Vargas, 1640',
    city: 'Belo Horizonte',
    state: 'Minas Gerais',
    country: 'Brazil',
    zipCode: '30170-044',
    latitude: -19.9278,
    longitude: -43.9422,
    rating: 4.9,
    totalRooms: 80,
    availableRooms: 8,
    pricePerNight: 650,
    currency: 'BRL',
    amenities: [
      'WiFi gratuito',
      'Ar condicionado',
      'Piscina',
      'Spa',
      'Restaurante gourmet',
      'Butler service',
      'Academia',
      'Estacionamento valet',
    ],
    images: [
      'https://example.com/fasano1.jpg',
      'https://example.com/fasano2.jpg',
    ],
    checkInTime: '15:00',
    checkOutTime: '12:00',
    cancellationPolicy: 'Cancelamento gratuito até 72 horas antes do check-in',
    breakfastIncluded: true,
    wifiIncluded: true,
    parkingIncluded: true,
    petFriendly: true,
    stars: 5,
  },
  {
    name: 'Quality Hotel Belo Horizonte',
    description: 'Contemporary hotel with excellent location and value',
    address: 'Rua Tamóios, 212',
    city: 'Belo Horizonte',
    state: 'Minas Gerais',
    country: 'Brazil',
    zipCode: '30112-000',
    latitude: -19.9389,
    longitude: -43.9367,
    rating: 4.0,
    totalRooms: 160,
    availableRooms: 78,
    pricePerNight: 220,
    currency: 'BRL',
    amenities: [
      'WiFi gratuito',
      'Ar condicionado',
      'Academia',
      'Business center',
      'Restaurante',
    ],
    images: [
      'https://example.com/quality1.jpg',
      'https://example.com/quality2.jpg',
    ],
    checkInTime: '14:00',
    checkOutTime: '11:00',
    cancellationPolicy: 'Cancelamento gratuito até 24 horas antes do check-in',
    breakfastIncluded: true,
    wifiIncluded: true,
    parkingIncluded: false,
    petFriendly: false,
    stars: 4,
  },
];

export async function seedHotels(): Promise<HotelEntity[]> {
  console.log('🌱 Seeding hotels...');

  const hotels: HotelEntity[] = [];

  for (const hotelData of hotelSeedData) {
    try {
      const hotel = HotelEntity.create(hotelData);
      hotels.push(hotel);
    } catch (error) {
      console.error(`Error creating hotel ${hotelData.name}:`, error);
    }
  }

  console.log(`✅ Created ${hotels.length} hotels`);
  return hotels;
}
