import { HotelEntity } from '../../domain/entities/hotel.entity';

export const hotelSeedData = [
  // ==============================================
  // HOTÉIS EM BELO HORIZONTE (50 hotéis)
  // ==============================================

  // Hotéis de Luxo (5 estrelas)
  {
    hotelId: 'bh-001',
    name: 'Tryp by Wyndham Belo Horizonte Savassi',
    nightly: 280.0,
    total: 560.0,
    rating: 4.6,
    policy: 'Cancelamento gratuito até 24h antes - Café da manhã incluído',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-002',
    name: 'Radisson Blu Belo Horizonte',
    nightly: 320.0,
    total: 640.0,
    rating: 4.5,
    policy: 'Cancelamento gratuito até 48h antes',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-003',
    name: 'Hotel Ouro Minas Palace',
    nightly: 450.0,
    total: 900.0,
    rating: 4.8,
    policy: 'Cancelamento gratuito até 72h antes',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-004',
    name: 'Grand Mercure Belo Horizonte Vila da Serra',
    nightly: 380.0,
    total: 760.0,
    rating: 4.7,
    policy: 'Cancelamento gratuito até 48h antes - Spa incluído',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-005',
    name: 'Hotel Fasano Belo Horizonte',
    nightly: 650.0,
    total: 1300.0,
    rating: 4.9,
    policy: 'Cancelamento gratuito até 72h antes - Serviço de concierge',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-006',
    name: 'Copacabana Hotel Belo Horizonte',
    nightly: 420.0,
    total: 840.0,
    rating: 4.6,
    policy: 'Cancelamento gratuito até 48h antes',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-007',
    name: 'Hotel Vila da Montanha',
    nightly: 520.0,
    total: 1040.0,
    rating: 4.8,
    policy: 'Cancelamento gratuito até 72h antes - Vista para a Serra',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-008',
    name: 'Mercure Belo Horizonte Lourdes',
    nightly: 340.0,
    total: 680.0,
    rating: 4.5,
    policy: 'Cancelamento gratuito até 24h antes',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },

  // Hotéis Executivos (4 estrelas)
  {
    hotelId: 'bh-009',
    name: 'Holiday Inn Express Belo Horizonte Afonso Pena',
    nightly: 195.0,
    total: 390.0,
    rating: 4.2,
    policy: 'Cancelamento gratuito até 24h antes - Café da manhã incluído',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-010',
    name: 'Intercity Belo Horizonte',
    nightly: 220.0,
    total: 440.0,
    rating: 4.3,
    policy: 'Cancelamento gratuito até 24h antes',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-011',
    name: 'Quality Hotel Afonso Pena',
    nightly: 210.0,
    total: 420.0,
    rating: 4.1,
    policy: 'Cancelamento gratuito até 24h antes - Fitness center incluído',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-012',
    name: 'Dayrell Hotel e Centro de Convenções',
    nightly: 260.0,
    total: 520.0,
    rating: 4.4,
    policy: 'Cancelamento gratuito até 48h antes',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-013',
    name: 'Hotel Sol Belo Horizonte',
    nightly: 180.0,
    total: 360.0,
    rating: 4.0,
    policy: 'Cancelamento gratuito até 24h antes',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-014',
    name: 'Comfort Suites Savassi',
    nightly: 240.0,
    total: 480.0,
    rating: 4.3,
    policy: 'Cancelamento gratuito até 24h antes - Café da manhã incluído',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-015',
    name: 'Novotel BH Savassi',
    nightly: 290.0,
    total: 580.0,
    rating: 4.4,
    policy: 'Cancelamento gratuito até 48h antes',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-016',
    name: 'San Diego Suítes Lourdes',
    nightly: 230.0,
    total: 460.0,
    rating: 4.2,
    policy: 'Cancelamento gratuito até 24h antes',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-017',
    name: 'Ibis Belo Horizonte Savassi',
    nightly: 165.0,
    total: 330.0,
    rating: 4.1,
    policy: 'Cancelamento gratuito até 18h antes',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-018',
    name: 'Hampton by Hilton Belo Horizonte Centro',
    nightly: 270.0,
    total: 540.0,
    rating: 4.5,
    policy: 'Cancelamento gratuito até 24h antes - Café da manhã incluído',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-019',
    name: 'Hotel Beaga Belo Horizonte',
    nightly: 185.0,
    total: 370.0,
    rating: 4.0,
    policy: 'Cancelamento gratuito até 24h antes',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-020',
    name: 'Royal Golden Hotel',
    nightly: 250.0,
    total: 500.0,
    rating: 4.3,
    policy: 'Cancelamento gratuito até 48h antes',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },

  // Hotéis Econômicos (3 estrelas)
  {
    hotelId: 'bh-021',
    name: 'Hotel Max Savassi',
    nightly: 140.0,
    total: 280.0,
    rating: 3.9,
    policy: 'Cancelamento gratuito até 24h antes',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-022',
    name: 'Hotel Financial',
    nightly: 150.0,
    total: 300.0,
    rating: 3.8,
    policy: 'Cancelamento gratuito até 24h antes - Centro da cidade',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-023',
    name: 'Hotel Sagres',
    nightly: 120.0,
    total: 240.0,
    rating: 3.7,
    policy: 'Cancelamento gratuito até 24h antes',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-024',
    name: 'Flat Bassano Vacance',
    nightly: 160.0,
    total: 320.0,
    rating: 4.0,
    policy: 'Cancelamento gratuito até 24h antes - Apartamento com cozinha',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-025',
    name: 'Hotel Wimbledon',
    nightly: 135.0,
    total: 270.0,
    rating: 3.8,
    policy: 'Cancelamento gratuito até 24h antes',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-026',
    name: 'Hotel Contorno',
    nightly: 110.0,
    total: 220.0,
    rating: 3.6,
    policy: 'Cancelamento gratuito até 24h antes - Localização central',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-027',
    name: 'Hotel Praia Mar',
    nightly: 125.0,
    total: 250.0,
    rating: 3.7,
    policy: 'Cancelamento gratuito até 24h antes',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-028',
    name: 'Liberty Palace Hotel',
    nightly: 170.0,
    total: 340.0,
    rating: 4.0,
    policy: 'Cancelamento gratuito até 24h antes - Café da manhã incluído',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-029',
    name: 'Hotel Amazonas',
    nightly: 145.0,
    total: 290.0,
    rating: 3.9,
    policy: 'Cancelamento gratuito até 24h antes',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-030',
    name: 'Hotel Belo Horizonte',
    nightly: 155.0,
    total: 310.0,
    rating: 3.8,
    policy: 'Cancelamento gratuito até 24h antes - Centro histórico',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },

  // Hotéis Modernos e Boutique
  {
    hotelId: 'bh-031',
    name: 'Hotel Othon Palace Belo Horizonte',
    nightly: 310.0,
    total: 620.0,
    rating: 4.4,
    policy: 'Cancelamento gratuito até 48h antes',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-032',
    name: 'Apart Hotel Tropical',
    nightly: 190.0,
    total: 380.0,
    rating: 4.1,
    policy: 'Cancelamento gratuito até 24h antes - Apartamento com cozinha',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-033',
    name: 'Rede Andrade Lourdes',
    nightly: 200.0,
    total: 400.0,
    rating: 4.2,
    policy: 'Cancelamento gratuito até 24h antes',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-034',
    name: 'Hotel Estação Savassi',
    nightly: 220.0,
    total: 440.0,
    rating: 4.3,
    policy: 'Cancelamento gratuito até 24h antes - Design moderno',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-035',
    name: 'Pousada do Areão',
    nightly: 175.0,
    total: 350.0,
    rating: 4.0,
    policy: 'Cancelamento gratuito até 24h antes - Ambiente familiar',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-036',
    name: 'Hotel Real Palace',
    nightly: 300.0,
    total: 600.0,
    rating: 4.4,
    policy: 'Cancelamento gratuito até 48h antes - Centro de convenções',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-037',
    name: 'San Diego Express Savassi',
    nightly: 180.0,
    total: 360.0,
    rating: 4.1,
    policy: 'Cancelamento gratuito até 24h antes',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-038',
    name: 'Hotel Alpina',
    nightly: 160.0,
    total: 320.0,
    rating: 3.9,
    policy: 'Cancelamento gratuito até 24h antes - Próximo ao Mineirão',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-039',
    name: 'Nacional Inn Belo Horizonte',
    nightly: 210.0,
    total: 420.0,
    rating: 4.2,
    policy: 'Cancelamento gratuito até 24h antes - Café da manhã incluído',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-040',
    name: 'Hotel Pousada Savassi',
    nightly: 140.0,
    total: 280.0,
    rating: 3.8,
    policy: 'Cancelamento gratuito até 24h antes - Ambiente acolhedor',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },

  // Hotéis Temáticos e Especiais
  {
    hotelId: 'bh-041',
    name: 'Hotel Mangabeiras',
    nightly: 290.0,
    total: 580.0,
    rating: 4.5,
    policy: 'Cancelamento gratuito até 48h antes - Vista para o Parque',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-042',
    name: 'Golden Tulip BH',
    nightly: 330.0,
    total: 660.0,
    rating: 4.6,
    policy: 'Cancelamento gratuito até 48h antes - Spa e academia',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-043',
    name: 'Flat Petúnia',
    nightly: 195.0,
    total: 390.0,
    rating: 4.1,
    policy: 'Cancelamento gratuito até 24h antes - Apartamento completo',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-044',
    name: 'Hotel Metropole',
    nightly: 165.0,
    total: 330.0,
    rating: 3.9,
    policy: 'Cancelamento gratuito até 24h antes - Centro histórico',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-045',
    name: 'Pampulha Design Hotel',
    nightly: 380.0,
    total: 760.0,
    rating: 4.7,
    policy: 'Cancelamento gratuito até 48h antes - Arquitetura moderna',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-046',
    name: 'Hotel Serrano',
    nightly: 245.0,
    total: 490.0,
    rating: 4.3,
    policy: 'Cancelamento gratuito até 24h antes - Vista para a Serra',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-047',
    name: 'Bristol Brasil 500 Hotel',
    nightly: 275.0,
    total: 550.0,
    rating: 4.4,
    policy: 'Cancelamento gratuito até 48h antes - Business center',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-048',
    name: 'Hotel Malaga',
    nightly: 155.0,
    total: 310.0,
    rating: 3.8,
    policy: 'Cancelamento gratuito até 24h antes - Ambiente familiar',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-049',
    name: 'Bourbon Convention Hotel',
    nightly: 350.0,
    total: 700.0,
    rating: 4.6,
    policy: 'Cancelamento gratuito até 48h antes - Centro de convenções',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },
  {
    hotelId: 'bh-050',
    name: 'Royal Savassi Boutique Hotel',
    nightly: 420.0,
    total: 840.0,
    rating: 4.8,
    policy: 'Cancelamento gratuito até 72h antes - Boutique experience',
    currency: 'BRL',
    city: 'Belo Horizonte',
  },

  // ==============================================
  // HOTÉIS EM SÃO PAULO (20 hotéis)
  // ==============================================

  {
    hotelId: 'sp-001',
    name: 'Hotel Unique',
    nightly: 850.0,
    total: 1700.0,
    rating: 4.9,
    policy: 'Cancelamento gratuito até 72h antes - Design icônico',
    currency: 'BRL',
    city: 'São Paulo',
  },
  {
    hotelId: 'sp-002',
    name: 'Renaissance São Paulo Hotel',
    nightly: 620.0,
    total: 1240.0,
    rating: 4.7,
    policy: 'Cancelamento gratuito até 48h antes',
    currency: 'BRL',
    city: 'São Paulo',
  },
  {
    hotelId: 'sp-003',
    name: 'Copacabana Hotel São Paulo',
    nightly: 480.0,
    total: 960.0,
    rating: 4.5,
    policy: 'Cancelamento gratuito até 48h antes',
    currency: 'BRL',
    city: 'São Paulo',
  },
  {
    hotelId: 'sp-004',
    name: 'Sheraton São Paulo WTC Hotel',
    nightly: 550.0,
    total: 1100.0,
    rating: 4.6,
    policy: 'Cancelamento gratuito até 48h antes',
    currency: 'BRL',
    city: 'São Paulo',
  },
  {
    hotelId: 'sp-005',
    name: 'Hotel Emiliano',
    nightly: 950.0,
    total: 1900.0,
    rating: 4.9,
    policy: 'Cancelamento gratuito até 72h antes - Luxo na Paulista',
    currency: 'BRL',
    city: 'São Paulo',
  },
  {
    hotelId: 'sp-006',
    name: 'Grand Hyatt São Paulo',
    nightly: 780.0,
    total: 1560.0,
    rating: 4.8,
    policy: 'Cancelamento gratuito até 72h antes',
    currency: 'BRL',
    city: 'São Paulo',
  },
  {
    hotelId: 'sp-007',
    name: 'Maksoud Plaza',
    nightly: 420.0,
    total: 840.0,
    rating: 4.4,
    policy: 'Cancelamento gratuito até 24h antes',
    currency: 'BRL',
    city: 'São Paulo',
  },
  {
    hotelId: 'sp-008',
    name: 'Novotel São Paulo Jaraguá Conventions',
    nightly: 380.0,
    total: 760.0,
    rating: 4.3,
    policy: 'Cancelamento gratuito até 24h antes',
    currency: 'BRL',
    city: 'São Paulo',
  },
  {
    hotelId: 'sp-009',
    name: 'Hilton São Paulo Morumbi',
    nightly: 650.0,
    total: 1300.0,
    rating: 4.7,
    policy: 'Cancelamento gratuito até 48h antes',
    currency: 'BRL',
    city: 'São Paulo',
  },
  {
    hotelId: 'sp-010',
    name: 'Marriott Executive Apartments São Paulo',
    nightly: 580.0,
    total: 1160.0,
    rating: 4.6,
    policy: 'Cancelamento gratuito até 48h antes - Apartamentos executivos',
    currency: 'BRL',
    city: 'São Paulo',
  },
  {
    hotelId: 'sp-011',
    name: 'InterContinental São Paulo',
    nightly: 720.0,
    total: 1440.0,
    rating: 4.8,
    policy: 'Cancelamento gratuito até 72h antes',
    currency: 'BRL',
    city: 'São Paulo',
  },
  {
    hotelId: 'sp-012',
    name: 'WZ Hotel Jardins',
    nightly: 390.0,
    total: 780.0,
    rating: 4.4,
    policy: 'Cancelamento gratuito até 24h antes - Jardins',
    currency: 'BRL',
    city: 'São Paulo',
  },
  {
    hotelId: 'sp-013',
    name: 'Blue Tree Premium Paulista',
    nightly: 460.0,
    total: 920.0,
    rating: 4.5,
    policy: 'Cancelamento gratuito até 48h antes - Avenida Paulista',
    currency: 'BRL',
    city: 'São Paulo',
  },
  {
    hotelId: 'sp-014',
    name: 'Holiday Inn Express São Paulo Vila Olímpia',
    nightly: 280.0,
    total: 560.0,
    rating: 4.2,
    policy: 'Cancelamento gratuito até 24h antes - Café da manhã incluído',
    currency: 'BRL',
    city: 'São Paulo',
  },
  {
    hotelId: 'sp-015',
    name: 'Comfort Hotel São Paulo',
    nightly: 240.0,
    total: 480.0,
    rating: 4.1,
    policy: 'Cancelamento gratuito até 24h antes',
    currency: 'BRL',
    city: 'São Paulo',
  },
  {
    hotelId: 'sp-016',
    name: 'Hotel Fasano São Paulo',
    nightly: 1200.0,
    total: 2400.0,
    rating: 5.0,
    policy: 'Cancelamento gratuito até 72h antes - Gastronomia de excelência',
    currency: 'BRL',
    city: 'São Paulo',
  },
  {
    hotelId: 'sp-017',
    name: 'Hotel Pestana São Paulo',
    nightly: 350.0,
    total: 700.0,
    rating: 4.3,
    policy: 'Cancelamento gratuito até 24h antes',
    currency: 'BRL',
    city: 'São Paulo',
  },
  {
    hotelId: 'sp-018',
    name: 'Ibis São Paulo Congonhas',
    nightly: 180.0,
    total: 360.0,
    rating: 4.0,
    policy: 'Cancelamento gratuito até 18h antes - Próximo ao aeroporto',
    currency: 'BRL',
    city: 'São Paulo',
  },
  {
    hotelId: 'sp-019',
    name: 'Tryp by Wyndham São Paulo Higienópolis',
    nightly: 320.0,
    total: 640.0,
    rating: 4.4,
    policy: 'Cancelamento gratuito até 24h antes',
    currency: 'BRL',
    city: 'São Paulo',
  },
  {
    hotelId: 'sp-020',
    name: "L'Hotel PortoBay São Paulo",
    nightly: 680.0,
    total: 1360.0,
    rating: 4.7,
    policy: 'Cancelamento gratuito até 48h antes - Vista panorâmica',
    currency: 'BRL',
    city: 'São Paulo',
  },

  // ==============================================
  // HOTÉIS EM SAN FRANCISCO (10 hotéis)
  // ==============================================

  {
    hotelId: 'sf-001',
    name: 'The St. Regis San Francisco',
    nightly: 950.0,
    total: 1900.0,
    rating: 4.9,
    policy: 'Free cancellation up to 48h before - Luxury downtown',
    currency: 'USD',
    city: 'San Francisco',
  },
  {
    hotelId: 'sf-002',
    name: 'Hotel Zephyr San Francisco',
    nightly: 420.0,
    total: 840.0,
    rating: 4.5,
    policy: "Free cancellation up to 24h before - Fisherman's Wharf",
    currency: 'USD',
    city: 'San Francisco',
  },
  {
    hotelId: 'sf-003',
    name: 'Grand Hyatt San Francisco',
    nightly: 680.0,
    total: 1360.0,
    rating: 4.7,
    policy: 'Free cancellation up to 48h before - Union Square',
    currency: 'USD',
    city: 'San Francisco',
  },
  {
    hotelId: 'sf-004',
    name: 'The Westin St. Francis San Francisco',
    nightly: 580.0,
    total: 1160.0,
    rating: 4.6,
    policy: 'Free cancellation up to 48h before - Historic landmark',
    currency: 'USD',
    city: 'San Francisco',
  },
  {
    hotelId: 'sf-005',
    name: 'Hotel Nikko San Francisco',
    nightly: 520.0,
    total: 1040.0,
    rating: 4.4,
    policy: 'Free cancellation up to 24h before - Japanese hospitality',
    currency: 'USD',
    city: 'San Francisco',
  },
  {
    hotelId: 'sf-006',
    name: 'Fairmont San Francisco',
    nightly: 750.0,
    total: 1500.0,
    rating: 4.8,
    policy: 'Free cancellation up to 72h before - Nob Hill luxury',
    currency: 'USD',
    city: 'San Francisco',
  },
  {
    hotelId: 'sf-007',
    name: "Hotel Zed Fisherman's Wharf",
    nightly: 280.0,
    total: 560.0,
    rating: 4.2,
    policy: 'Free cancellation up to 24h before - Boutique style',
    currency: 'USD',
    city: 'San Francisco',
  },
  {
    hotelId: 'sf-008',
    name: 'InterContinental San Francisco',
    nightly: 820.0,
    total: 1640.0,
    rating: 4.8,
    policy: 'Free cancellation up to 48h before - SOMA district',
    currency: 'USD',
    city: 'San Francisco',
  },
  {
    hotelId: 'sf-009',
    name: 'Hotel Emblem San Francisco',
    nightly: 380.0,
    total: 760.0,
    rating: 4.3,
    policy: 'Free cancellation up to 24h before - Literary themed',
    currency: 'USD',
    city: 'San Francisco',
  },
  {
    hotelId: 'sf-010',
    name: 'The Ritz-Carlton San Francisco',
    nightly: 1100.0,
    total: 2200.0,
    rating: 5.0,
    policy: 'Free cancellation up to 72h before - Ultimate luxury',
    currency: 'USD',
    city: 'San Francisco',
  },
];

export async function seedHotels(): Promise<HotelEntity[]> {
  console.log('🌱 Seeding hotels...');

  const hotels: HotelEntity[] = [];

  for (const hotelData of hotelSeedData) {
    try {
      const hotel = HotelEntity.create(hotelData);
      hotels.push(hotel);
    } catch (error) {
      console.error(`Error creating hotel ${hotelData.hotelId}:`, error);
    }
  }

  console.log(`✅ Created ${hotels.length} hotels`);
  console.log(`   • 50 hotéis em Belo Horizonte`);
  console.log(`   • 20 hotéis em São Paulo`);
  console.log(`   • 10 hotéis em San Francisco`);
  return hotels;
}
