import { HotelEntity } from '../../domain/entities/hotel.entity';

const HOTELS_DATABASE = [
  // Hotéis em Belo Horizonte
  {
    hotelId: "bh-001",
    name: "Tryp by Wyndham Belo Horizonte Savassi",
    nightly: 280.0,
    total: 560.0,
    rating: 4.6,
    policy: "Cancelamento gratuito até 24h antes - Café da manhã incluído",
    currency: "BRL",
    city: "Belo Horizonte",
    state: "Minas Gerais",
    country: "Brazil",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400",
    address: "Rua Antônio de Albuquerque, 335 - Savassi",
    zipCode: "30112-010",
    breakfastIncluded: true,
    description: "Hotel moderno no coração de Savassi, próximo aos melhores restaurantes e bares da cidade."
  },
  {
    hotelId: "bh-002",
    name: "Radisson Blu Belo Horizonte",
    nightly: 320.0,
    total: 640.0,
    rating: 4.5,
    policy: "Cancelamento gratuito até 48h antes",
    currency: "BRL",
    city: "Belo Horizonte",
    state: "Minas Gerais",
    country: "Brazil",
    image: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=400",
    address: "Av. Bias Fortes, 382 - Centro",
    zipCode: "30112-000",
    description: "Hotel de luxo com vista para a Serra do Curral e serviços premium."
  },
  {
    hotelId: "bh-003",
    name: "Holiday Inn Express Belo Horizonte Afonso Pena",
    nightly: 195.0,
    total: 390.0,
    rating: 4.2,
    policy: "Cancelamento gratuito até 24h antes - Café da manhã incluído",
    currency: "BRL",
    city: "Belo Horizonte",
    state: "Minas Gerais",
    country: "Brazil",
    image: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=400",
    address: "Av. Afonso Pena, 1901 - Centro",
    zipCode: "30130-005",
    breakfastIncluded: true,
    description: "Hotel prático e confortável na principal avenida de Belo Horizonte."
  },
  {
    hotelId: "bh-004",
    name: "Mercure Belo Horizonte Vila da Serra",
    nightly: 380.0,
    total: 760.0,
    rating: 4.7,
    policy: "Cancelamento gratuito até 72h antes",
    currency: "BRL",
    city: "Belo Horizonte",
    state: "Minas Gerais",
    country: "Brazil",
    image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=400",
    address: "Av. Alameda da Serra, 1000 - Vila da Serra",
    zipCode: "34000-000",
    description: "Resort urbano com spa, piscina e vista panorâmica da cidade."
  },
  {
    hotelId: "bh-005",
    name: "ibis Belo Horizonte Liberdade",
    nightly: 140.0,
    total: 280.0,
    rating: 3.9,
    policy: "Cancelamento gratuito até 18h do dia da chegada",
    currency: "BRL",
    city: "Belo Horizonte",
    state: "Minas Gerais",
    country: "Brazil",
    image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=400",
    address: "Rua dos Tamoios, 212 - Centro",
    zipCode: "30112-000",
    description: "Hotel econômico com boa localização e serviços essenciais."
  },
  {
    hotelId: "bh-006",
    name: "Hotel Fasano Belo Horizonte",
    nightly: 650.0,
    total: 1300.0,
    rating: 4.9,
    policy: "Não reembolsável - Serviço de concierge 24h",
    currency: "BRL",
    city: "Belo Horizonte",
    state: "Minas Gerais",
    country: "Brazil",
    image: "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=400",
    address: "Av. Getúlio Vargas, 1640 - Funcionários",
    zipCode: "30112-021",
    description: "Hotel de luxo com design sofisticado, restaurante premiado e spa."
  },
  {
    hotelId: "bh-007",
    name: "Quality Hotel Afonso Pena",
    nightly: 165.0,
    total: 330.0,
    rating: 4.1,
    policy: "Cancelamento gratuito até 24h antes",
    currency: "BRL",
    city: "Belo Horizonte",
    state: "Minas Gerais",
    country: "Brazil",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400",
    address: "Av. Afonso Pena, 1050 - Centro",
    zipCode: "30130-002",
    description: "Hotel com boa relação custo-benefício no centro de BH."
  },
  // Hotéis em San Francisco
  {
    hotelId: "sfo-001",
    name: "Grand Hyatt San Francisco",
    nightly: 350.0,
    total: 3150.0,
    rating: 4.5,
    policy: "Cancelamento gratuito até 24h antes",
    currency: "USD",
    city: "San Francisco",
    state: "California",
    country: "United States",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400",
    address: "345 Stockton St, San Francisco, CA",
    zipCode: "94108",
    description: "Luxury hotel in the heart of Union Square with world-class amenities."
  },
  {
    hotelId: "sfo-002",
    name: "Hotel Zephyr San Francisco",
    nightly: 280.0,
    total: 2520.0,
    rating: 4.2,
    policy: "Cancelamento gratuito até 48h antes",
    currency: "USD",
    city: "San Francisco",
    state: "California",
    country: "United States",
    image: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=400",
    address: "Pier 39, Fisherman's Wharf, San Francisco, CA",
    zipCode: "94133",
    description: "Waterfront hotel with nautical theme and bay views."
  },
  {
    hotelId: "sfo-003",
    name: "The Ritz-Carlton San Francisco",
    nightly: 650.0,
    total: 5850.0,
    rating: 4.8,
    policy: "Não reembolsável",
    currency: "USD",
    city: "San Francisco",
    state: "California",
    country: "United States",
    image: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=400",
    address: "600 Stockton St, San Francisco, CA",
    zipCode: "94108",
    description: "Iconic luxury hotel atop Nob Hill with panoramic city views."
  },
];

export async function seedHotels(): Promise<any[]> {
  return HOTELS_DATABASE.map(hotel => ({
    id: crypto.randomUUID(),
    hotelId: hotel.hotelId,
    name: hotel.name,
    description: hotel.description,
    address: hotel.address,
    city: hotel.city,
    state: hotel.state,
    country: hotel.country,
    zipCode: hotel.zipCode,
    rating: hotel.rating,
    nightly: hotel.nightly,
    total: hotel.total,
    currency: hotel.currency,
    policy: hotel.policy,
    image: hotel.image,
    totalRooms: 100,
    availableRooms: Math.floor(Math.random() * 50) + 10,
    amenities: [
      "Wi-Fi Gratuito",
      "Ar Condicionado",
      "TV a Cabo",
      ...(hotel.breakfastIncluded ? ["Café da Manhã"] : []),
      ...(Math.random() > 0.5 ? ["Academia"] : []),
      ...(Math.random() > 0.6 ? ["Piscina"] : []),
      ...(Math.random() > 0.7 ? ["Spa"] : [])
    ],
    checkInTime: "14:00",
    checkOutTime: "12:00",
    breakfastIncluded: hotel.breakfastIncluded || false,
    wifiIncluded: true,
    parkingIncluded: Math.random() > 0.5,
    petFriendly: Math.random() > 0.7,
    stars: Math.ceil(hotel.rating)
  }));
}