import { HotelEntity } from '../../domain/entities/hotel.entity';

const HOTELS_DATABASE = [
  // Hotéis em Belo Horizonte
  {
    hotelId: "bh-001",
    name: "Tryp by Wyndham Belo Horizonte Savassi",
    nightly: 280.0,
    total: 560.0, // 2 nights (28/09 - 30/09)
    rating: 4.6,
    policy: "Cancelamento gratuito até 24h antes - Café da manhã incluído",
    currency: "BRL",
    city: "Belo Horizonte",
    state: "Minas Gerais",
    country: "Brazil",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400",
    address: "Rua Antônio de Albuquerque, 335 - Savassi",
    zipCode: "30112-010",
    breakfastIncluded: true,
    description: "Hotel moderno no coração de Savassi, próximo aos melhores restaurantes e bares da cidade."
  },
  {
    hotelId: "bh-002",
    name: "Radisson Blu Belo Horizonte",
    nightly: 320.0,
    total: 640.0,
    rating: 4.5,
    policy: "Cancelamento gratuito até 48h antes",
    currency: "BRL",
    city: "Belo Horizonte",
    state: "Minas Gerais",
    country: "Brazil",
    image: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=400",
    address: "Av. Bias Fortes, 382 - Centro",
    zipCode: "30112-000",
    description: "Hotel de luxo com vista para a Serra do Curral e serviços premium."
  },
  {
    hotelId: "bh-003",
    name: "Holiday Inn Express Belo Horizonte Afonso Pena",
    nightly: 195.0,
    total: 390.0,
    rating: 4.2,
    policy: "Cancelamento gratuito até 24h antes - Café da manhã incluído",
    currency: "BRL",
    city: "Belo Horizonte",
    state: "Minas Gerais",
    country: "Brazil",
    image: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=400",
    address: "Av. Afonso Pena, 1901 - Centro",
    zipCode: "30130-005",
    breakfastIncluded: true,
    description: "Hotel prático e confortável na principal avenida de Belo Horizonte."
  },
  {
    hotelId: "bh-004",
    name: "Mercure Belo Horizonte Vila da Serra",
    nightly: 380.0,
    total: 760.0,
    rating: 4.7,
    policy: "Cancelamento gratuito até 72h antes",
    currency: "BRL",
    city: "Belo Horizonte",
    state: "Minas Gerais",
    country: "Brazil",
    image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=400",
    address: "Av. Alameda da Serra, 1000 - Vila da Serra",
    zipCode: "34000-000",
    description: "Resort urbano com spa, piscina e vista panorâmica da cidade."
  },
  {
    hotelId: "bh-005",
    name: "ibis Belo Horizonte Liberdade",
    nightly: 140.0,
    total: 280.0,
    rating: 3.9,
    policy: "Cancelamento gratuito até 18h do dia da chegada",
    currency: "BRL",
    city: "Belo Horizonte",
    state: "Minas Gerais",
    country: "Brazil",
    image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=400",
    address: "Rua dos Tamoios, 212 - Centro",
    zipCode: "30112-000",
    description: "Hotel econômico com boa localização e serviços essenciais."
  },
  {
    hotelId: "bh-006",
    name: "Hotel Fasano Belo Horizonte",
    nightly: 650.0,
    total: 1300.0,
    rating: 4.9,
    policy: "Não reembolsável - Serviço de concierge 24h",
    currency: "BRL",
    city: "Belo Horizonte",
    state: "Minas Gerais",
    country: "Brazil",
    image: "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=400",
    address: "Av. Getúlio Vargas, 1640 - Funcionários",
    zipCode: "30112-021",
    description: "Hotel de luxo com design sofisticado, restaurante premiado e spa."
  },
  {
    hotelId: "bh-007",
    name: "Quality Hotel Afonso Pena",
    nightly: 165.0,
    total: 330.0,
    rating: 4.1,
    policy: "Cancelamento gratuito até 24h antes",
    currency: "BRL",
    city: "Belo Horizonte",
    state: "Minas Gerais",
    country: "Brazil",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400",
    address: "Av. Afonso Pena, 1050 - Centro",
    zipCode: "30130-002",
    description: "Hotel com boa relação custo-benefício no centro de BH."
  },
  // Hotéis em San Francisco (mantidos para compatibilidade)
  {
    hotelId: "sfo-001",
    name: "Grand Hyatt San Francisco",
    nightly: 350.0,
    total: 3150.0, // 9 nights
    rating: 4.5,
    policy: "Cancelamento gratuito até 24h antes",
    currency: "USD",
    city: "San Francisco",
    state: "California",
    country: "United States",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400",
    address: "345 Stockton St, San Francisco, CA",
    zipCode: "94108",
    description: "Luxury hotel in the heart of Union Square with world-class amenities."
  },
  {
    hotelId: "sfo-002",
    name: "Hotel Zephyr San Francisco",
    nightly: 280.0,
    total: 2520.0,
    rating: 4.2,
    policy: "Cancelamento gratuito até 48h antes",
    currency: "USD",
    city: "San Francisco",
    state: "California",
    country: "United States",
    image: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=400",
    address: "Pier 39, Fisherman's Wharf, San Francisco, CA",
    zipCode: "94133",
    description: "Waterfront hotel with nautical theme and bay views."
  },
  {
    hotelId: "sfo-003",
    name: "The Ritz-Carlton San Francisco",
    nightly: 650.0,
    total: 5850.0,
    rating: 4.8,
    policy: "Não reembolsável",
    currency: "USD",
    city: "San Francisco",
    state: "California",
    country: "United States",
    image: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=400",
    address: "600 Stockton St, San Francisco, CA",
    zipCode: "94108",
    description: "Iconic luxury hotel atop Nob Hill with panoramic city views."
  },
];

export async function seedHotels(): Promise<HotelEntity[]> {
    currency: 'BRL',
    amenities: [
      'WiFi gratuito',
      'Ar condicionado',
      'Piscina',
      'Spa',
      'Academia',
      'Business center',
    ],
    images: [
      'https://example.com/radisson1.jpg',
      'https://example.com/radisson2.jpg',
    ],
    checkInTime: '15:00',
    checkOutTime: '12:00',
    cancellationPolicy: 'Cancelamento gratuito até 48 horas antes do check-in',
    breakfastIncluded: true,
    wifiIncluded: true,
    parkingIncluded: true,
    petFriendly: true,
    stars: 5,
  },
  {
    name: 'Holiday Inn Express Belo Horizonte',
    description:
      'Comfortable and convenient hotel perfect for business travelers',
    address: 'Rua Curitiba, 1000',
    city: 'Belo Horizonte',
    state: 'Minas Gerais',
    country: 'Brazil',
    zipCode: '30170-120',
    latitude: -19.9245,
    longitude: -43.9445,
    rating: 4.1,
    totalRooms: 200,
    availableRooms: 89,
    pricePerNight: 195,
    currency: 'BRL',
    amenities: [
      'WiFi gratuito',
      'Ar condicionado',
      'Academia',
      'Business center',
    ],
    images: [
      'https://example.com/holiday1.jpg',
      'https://example.com/holiday2.jpg',
    ],
    checkInTime: '15:00',
    checkOutTime: '11:00',
    cancellationPolicy: 'Cancelamento gratuito até 18 horas antes do check-in',
    breakfastIncluded: true,
    wifiIncluded: true,
    parkingIncluded: false,
    petFriendly: false,
    stars: 3,
  },
  {
    name: 'Mercure Belo Horizonte Lourdes',
    description: 'Sophisticated hotel in the upscale Lourdes neighborhood',
    address: 'Rua Gonçalves Dias, 394',
    city: 'Belo Horizonte',
    state: 'Minas Gerais',
    country: 'Brazil',
    zipCode: '30140-091',
    latitude: -19.9311,
    longitude: -43.9455,
    rating: 4.3,
    totalRooms: 150,
    availableRooms: 67,
    pricePerNight: 320,
    currency: 'BRL',
    amenities: [
      'WiFi gratuito',
      'Ar condicionado',
      'Restaurante',
      'Bar',
      'Academia',
      'Room service',
    ],
    images: [
      'https://example.com/mercure1.jpg',
      'https://example.com/mercure2.jpg',
    ],
    checkInTime: '14:00',
    checkOutTime: '12:00',
    cancellationPolicy: 'Cancelamento gratuito até 24 horas antes do check-in',
    breakfastIncluded: false,
    wifiIncluded: true,
    parkingIncluded: true,
    petFriendly: false,
    stars: 4,
  },
  {
    name: 'ibis Belo Horizonte Centro',
    description:
      'Budget-friendly hotel with modern amenities in downtown location',
    address: 'Rua dos Tupis, 640',
    city: 'Belo Horizonte',
    state: 'Minas Gerais',
    country: 'Brazil',
    zipCode: '30190-060',
    latitude: -19.9167,
    longitude: -43.9345,
    rating: 3.9,
    totalRooms: 240,
    availableRooms: 156,
    pricePerNight: 140,
    currency: 'BRL',
    amenities: [
      'WiFi gratuito',
      'Ar condicionado',
      'Restaurante',
      'Bar',
      'Recepção 24h',
    ],
    images: ['https://example.com/ibis1.jpg', 'https://example.com/ibis2.jpg'],
    checkInTime: '14:00',
    checkOutTime: '12:00',
    cancellationPolicy: 'Cancelamento gratuito até 18 horas antes do check-in',
    breakfastIncluded: false,
    wifiIncluded: true,
    parkingIncluded: false,
    petFriendly: false,
    stars: 3,
  },
  {
    name: 'Hotel Fasano Belo Horizonte',
    description:
      'Ultra-luxury hotel offering world-class service and amenities',
    address: 'Avenida Getúlio Vargas, 1640',
    city: 'Belo Horizonte',
    state: 'Minas Gerais',
    country: 'Brazil',
    zipCode: '30170-044',
    latitude: -19.9278,
    longitude: -43.9422,
    rating: 4.9,
    totalRooms: 80,
    availableRooms: 8,
    pricePerNight: 650,
    currency: 'BRL',
    amenities: [
      'WiFi gratuito',
      'Ar condicionado',
      'Piscina',
      'Spa',
      'Restaurante gourmet',
      'Butler service',
      'Academia',
      'Estacionamento valet',
    ],
    images: [
      'https://example.com/fasano1.jpg',
      'https://example.com/fasano2.jpg',
    ],
    checkInTime: '15:00',
    checkOutTime: '12:00',
    cancellationPolicy: 'Cancelamento gratuito até 72 horas antes do check-in',
    breakfastIncluded: true,
    wifiIncluded: true,
    parkingIncluded: true,
    petFriendly: true,
    stars: 5,
  },
  {
    name: 'Quality Hotel Belo Horizonte',
    description: 'Contemporary hotel with excellent location and value',
    address: 'Rua Tamóios, 212',
    city: 'Belo Horizonte',
    state: 'Minas Gerais',
    country: 'Brazil',
    zipCode: '30112-000',
    latitude: -19.9389,
    longitude: -43.9367,
    rating: 4.0,
    totalRooms: 160,
    availableRooms: 78,
    pricePerNight: 220,
    currency: 'BRL',
    amenities: [
      'WiFi gratuito',
      'Ar condicionado',
      'Academia',
      'Business center',
      'Restaurante',
    ],
    images: [
      'https://example.com/quality1.jpg',
      'https://example.com/quality2.jpg',
    ],
    checkInTime: '14:00',
    checkOutTime: '11:00',
    cancellationPolicy: 'Cancelamento gratuito até 24 horas antes do check-in',
    breakfastIncluded: true,
    wifiIncluded: true,
    parkingIncluded: false,
    petFriendly: false,
    stars: 4,
  },
];

export async function seedHotels(): Promise<HotelEntity[]> {
  console.log('🌱 Seeding hotels...');

  const hotels: HotelEntity[] = [];

  for (const hotelData of hotelSeedData) {
    try {
      const hotel = HotelEntity.create(hotelData);
      hotels.push(hotel);
    } catch (error) {
      console.error(`Error creating hotel ${hotelData.name}:`, error);
    }
  }

  console.log(`✅ Created ${hotels.length} hotels`);
  return hotels;
}
